# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Nomandia.cn # 标题
subtitle: 'FlY WitH YoU' # 副标题
description: '触碰未来科技、凝汇生活点滴' # SEO描述
keywords: nomandia # 关键字
author: Nomandia #  作者名
language: zh-CN  # 语言
timezone: 'Asia/Shanghai' # 时区

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://nomandia.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source # 资源文件夹
public_dir: public # 发布文件夹
tag_dir: tags # 标签根目录
archive_dir: archives # 归档根目录
category_dir: categories # 分类根目录
code_dir: downloads/code # include code文件夹, source_dir下子目录
i18n_dir: :lang # 国际化文件夹
skip_render: # 跳过渲染直接复制到public文件夹

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post # 默认的页面布局/scafflolds/*
auto_spacing: true # 中英文间增加空格
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false # 显示草稿夹
post_asset_folder: false
relative_link: false # 链接设为根目录的相对路径
future: true # 显示未来的文章
highlight: # 代码高亮
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized # 默认的分类
category_map: # 分类别名
  前端: frontend
tag_map: # 标签别名
  Go: go

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/nomandia/nomandia.github.io.git
  branch: master
  message: Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}
  token: ab983c6713c4e2d5c4c26550746e69fdb0e48a49

# Feed
# https://github.com/hexojs/hexo-generator-feed
plugin:
  - hexo-generator-feed
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 10
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# hexo-neat
# https://github.com/rozbo/hexo-neat
# 注意事项：
# 1. 不要跳过压缩.md文件这会导致解析错误
# 2. 不要跳过.swig文件，这个相当于模板页跳过后就没法压缩了
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css
neat_css:
  enable: true
  exclude:
#    - '**/*.min.css' # 跳过所有的min.css
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'